spring.application.name=employee-service
server.port=8081
spring.mongodb.uri=mongodb://localhost:27017/employee_service_db

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=127.0.0.1

spring.cloud.openfeign.client.config.department-service.connectTimeout=2000
spring.cloud.openfeign.client.config.department-service.readTimeout=3000

logging.level.feign=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG

spring.cloud.loadbalancer.retry.enabled=true
spring.cloud.loadbalancer.retry.max-retries-on-same-service-instance=2
spring.cloud.loadbalancer.retry.max-retries-on-next-service-instance=1

resilience4j.circuitbreaker.instances.departmentService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.departmentService.sliding-window-size=5
resilience4j.circuitbreaker.instances.departmentService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.departmentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.departmentService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.departmentService.permitted-number-of-calls-in-half-open-state=2